title: intriduction
author: GitHub User fejro
email: fejiroakpoguma@yahoo.com
description: > # this means to ignore newlines until "baseurl:"
 i am 19 years old. i am aries and i love ariana grande
# social links
twitter_username: f3jir0 # DO NOT include the @ character, or else the build will fail!
github_username:  fejiroishere # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
theme: minima
